"use strict";

// Hardcoded test puzzle: a singles-only puzzle generated by the Rust engine
// (`cargo run --release --example gen_cache -- --target hidden-single --mode
// train --method random --n 1 --seed 7`). This is a placeholder for the
// first playable slice — it will be replaced by on-device wasm generation.
// `solution` is unused for now; it's kept for the upcoming mistake-checking
// feature so the UI never has to solve anything itself.
const PUZZLE = {
  puzzle:   "..6.....151...46..4....9.7....7.....7...58...2...3.79....54.....6.8..4...3......9",
  solution: "376285941519374682482169375698712534743958216251436798927541863165893427834627159",
};

const N = 81;

// ---- State ----
// `given[i]`  : 1..9 for a clue, 0 otherwise (immutable).
// `value[i]`  : 1..9 for a user-placed digit, 0 if empty.
// `marks[i]`  : Set of candidate digits the player has pencilled in.
const given = new Array(N).fill(0);
const value = new Array(N).fill(0);
const marks = Array.from({ length: N }, () => new Set());

let selected = null;     // index 0..80, or null
let notesMode = false;
let activeDigit = 0;     // 1..9 when a digit is "pen-locked" (highlight mode), 0 otherwise

const cells = [];        // DOM nodes, index 0..80
const digitBtns = [];    // DOM nodes, index 0..8 -> digit 1..9

const boardEl = document.getElementById("board");
const notesBtn = document.getElementById("notes");
const undoBtn = document.getElementById("undo");

// ---- Undo history ----
// Each entry is a full snapshot of the editable state (values + pencil marks)
// taken *before* a change. `commit` records one only when a mutation actually
// changes the board, so no-op taps don't waste an undo step. The optimistic
// double-tap rollbacks reuse this same stack (see onCellTap / onDigitTap), so a
// place->convert double-tap collapses to a single undo step.
const history = [];

function snapshot() {
  return { v: value.slice(), m: marks.map((s) => new Set(s)) };
}

function applySnapshot(s) {
  for (let i = 0; i < N; i++) {
    value[i] = s.v[i];
    marks[i] = new Set(s.m[i]);
  }
}

function boardMatches(s) {
  for (let i = 0; i < N; i++) {
    if (value[i] !== s.v[i]) return false;
    if (marks[i].size !== s.m[i].size) return false;
    for (const d of marks[i]) if (!s.m[i].has(d)) return false;
  }
  return true;
}

// Run a board mutation, recording it for undo iff it changed anything.
// Returns whether an entry was pushed.
function commit(mutate) {
  const before = snapshot();
  mutate();
  if (boardMatches(before)) return false;
  history.push(before);
  updateUndoButton();
  return true;
}

function undo() {
  if (history.length === 0) return;
  applySnapshot(history.pop());
  updateUndoButton();
  render();
}

function updateUndoButton() {
  if (undoBtn) undoBtn.disabled = history.length === 0;
}

// ---- Setup ----
function parseGivens() {
  for (let i = 0; i < N; i++) {
    const ch = PUZZLE.puzzle[i];
    given[i] = ch >= "1" && ch <= "9" ? Number(ch) : 0;
  }
}

function buildBoard() {
  for (let i = 0; i < N; i++) {
    const r = Math.floor(i / 9);
    const c = i % 9;
    const cell = document.createElement("div");
    cell.className = "cell";
    cell.dataset.idx = i;
    cell.setAttribute("role", "gridcell");
    if (c === 8) cell.classList.add("col8");
    if (r === 8) cell.classList.add("row8");
    if (c === 2 || c === 5) cell.classList.add("boxr");
    if (r === 2 || r === 5) cell.classList.add("boxb");

    const valueEl = document.createElement("span");
    valueEl.className = "value";
    const marksEl = document.createElement("div");
    marksEl.className = "marks";
    for (let d = 1; d <= 9; d++) {
      const m = document.createElement("span");
      m.dataset.d = d;
      marksEl.appendChild(m);
    }
    cell.appendChild(marksEl);
    cell.appendChild(valueEl);

    cell.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      onCellTap(i);
    });

    boardEl.appendChild(cell);
    cells.push(cell);
  }
}

// ---- Peer relationship (row / col / box) for selection highlighting. ----
function isPeer(a, b) {
  if (a === b) return false;
  const ra = Math.floor(a / 9), ca = a % 9;
  const rb = Math.floor(b / 9), cb = b % 9;
  if (ra === rb || ca === cb) return true;
  const sameBox =
    Math.floor(ra / 3) === Math.floor(rb / 3) &&
    Math.floor(ca / 3) === Math.floor(cb / 3);
  return sameBox;
}

function digitAt(i) {
  return given[i] || value[i];
}

// ---- Rendering ----
function render() {
  // The highlighted digit is the pen-locked digit if any, else whatever sits
  // in the selected cell.
  const highlightDigit =
    activeDigit !== 0 ? activeDigit : selected !== null ? digitAt(selected) : 0;

  for (let i = 0; i < N; i++) {
    const cell = cells[i];
    const valueEl = cell.querySelector(".value");
    const d = digitAt(i);

    cell.classList.toggle("given", given[i] !== 0);

    if (d !== 0) {
      valueEl.textContent = d;
      cell.classList.add("filled");
    } else {
      valueEl.textContent = "";
      cell.classList.remove("filled");
    }

    // Pencil marks only show on an empty cell.
    const markSpans = cell.querySelectorAll(".marks span");
    for (const span of markSpans) {
      const show = d === 0 && marks[i].has(Number(span.dataset.d));
      span.textContent = show ? span.dataset.d : "";
    }

    // Highlight classes.
    cell.classList.toggle("selected", i === selected);
    cell.classList.toggle("peer", selected !== null && isPeer(selected, i));
    cell.classList.toggle(
      "same",
      highlightDigit !== 0 && i !== selected && d === highlightDigit
    );
  }
}

function updateDigitButtons() {
  for (let k = 0; k < 9; k++) {
    digitBtns[k].classList.toggle("active", activeDigit === k + 1);
  }
}

// ---- Actions ----
function select(i) {
  selected = i;
  render();
}

// Cell-tap state for pen-lock double-tap detection (place <-> note).
let lastCell = -1;
let lastCellTime = 0;
let cellSinglePushed = false; // the last cell single-tap recorded an undo entry

// Board tap. Without a pen-locked digit this just selects the cell. With one,
// a tap places that digit (no selection highlight needed while placing), and a
// double-tap on the same cell instead applies the opposite mode — so if normal
// taps place values, double-tapping pencils a mark, and vice-versa.
function onCellTap(i) {
  if (activeDigit === 0) {
    select(i);
    return;
  }

  const now = performance.now();
  const isDouble = i === lastCell && now - lastCellTime < DOUBLE_MS;
  lastCellTime = now;

  if (isDouble) {
    lastCell = -1; // don't let a third quick tap read as another double
    // Roll the single tap back, then commit the opposite as one undo step.
    if (cellSinglePushed) {
      applySnapshot(history.pop());
      cellSinglePushed = false;
      updateUndoButton();
    }
    commit(() => applyOppositeToCell(i, activeDigit)); // the other thing
    render();
    return;
  }

  lastCell = i;
  cellSinglePushed = commit(() => applyDigitToCell(i, activeDigit));
  render();
}

function moveSelection(dr, dc) {
  if (selected === null) {
    select(0);
    return;
  }
  let r = Math.floor(selected / 9) + dr;
  let c = (selected % 9) + dc;
  r = (r + 9) % 9;
  c = (c + 9) % 9;
  select(r * 9 + c);
}

// Place / toggle a digit (or pencil mark) into a specific cell, per the global
// Notes mode. Clues are locked. Shared by the digit pad (cell-first) and the
// pen-lock single tap (digit-first).
function applyDigitToCell(i, d) {
  if (given[i] !== 0) return;
  if (notesMode) {
    // Pencil marks are meaningless once a value is placed.
    if (value[i] !== 0) return;
    const set = marks[i];
    if (set.has(d)) set.delete(d);
    else set.add(d);
  } else {
    // Toggle off if re-entering the same digit; placing clears pencil marks.
    value[i] = value[i] === d ? 0 : d;
    marks[i].clear();
  }
}

// The pen-lock double-tap action: the opposite of a normal tap. If normal taps
// place values, this pencils a mark — clearing any placed value first so the
// mark is actually visible (a value would otherwise hide it). If normal taps
// pencil marks, this places the value instead.
function applyOppositeToCell(i, d) {
  if (given[i] !== 0) return;
  if (notesMode) {
    value[i] = value[i] === d ? 0 : d;
    marks[i].clear();
  } else {
    value[i] = 0;
    const set = marks[i];
    if (set.has(d)) set.delete(d);
    else set.add(d);
  }
}

function inputDigit(d) {
  if (selected === null) return false;
  const pushed = commit(() => applyDigitToCell(selected, d));
  render();
  return pushed;
}

// Set the pen-locked digit (0 clears it) and refresh the highlight.
function setLock(d) {
  activeDigit = d;
  if (activeDigit !== 0) selected = null; // pen mode owns the highlight
  updateDigitButtons();
  render();
}

function erase() {
  if (selected === null) return;
  commit(() => {
    if (given[selected] !== 0) return;
    value[selected] = 0;
    marks[selected].clear();
  });
  render();
}

function toggleNotes() {
  notesMode = !notesMode;
  notesBtn.setAttribute("aria-pressed", String(notesMode));
}

// Clear all of the player's work and return to the puzzle's starting clues.
// (The clues themselves live in `given`, so we only wipe the editable state.)
function restart() {
  for (let i = 0; i < N; i++) {
    value[i] = 0;
    marks[i] = new Set();
  }
  history.length = 0;
  selected = null;
  activeDigit = 0;
  notesMode = false;
  // Reset double-tap gesture state so a stray pending double can't pop the
  // now-empty undo stack.
  lastDigit = 0;
  lastCell = -1;
  firstTapWasLocked = false;
  digitSinglePushed = false;
  cellSinglePushed = false;

  notesBtn.setAttribute("aria-pressed", "false");
  updateDigitButtons();
  updateUndoButton();
  render();
}

// ---- Hint (wasm bridge) ----
// Trunk initializes the wasm-bindgen module and exposes its exports on
// `window.wasmBindings`, firing `TrunkApplicationStarted` once ready. We grab
// the bindings then; the Hint button only does anything after that point.
let wasm = null;
window.addEventListener("TrunkApplicationStarted", () => {
  wasm = window.wasmBindings;
});

// The solver returns raw cell indices / 0-based houses; the UI owns the labels.
function cellName(i) {
  return `R${Math.floor(i / 9) + 1}C${(i % 9) + 1}`;
}

function houseLabel(house) {
  const kind = { row: "row", col: "column", box: "box" }[house.kind] || house.kind;
  return `${kind} ${house.index + 1}`;
}

function deductionText(d) {
  return `${cellName(d.cell)} ${d.kind === "place" ? "=" : "≠"} ${d.digit}`;
}

function escapeHtml(s) {
  return s.replace(
    /[&<>"']/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]
  );
}

// Read the board out of the UI, ask the solver for every available step, and
// list them in the pop-up. Read-only: the board is never modified.
function showHint() {
  const dialog = document.getElementById("hintDialog");
  const title = document.getElementById("hintTitle");
  const body = document.getElementById("hintBody");
  const note = (msg) => {
    body.innerHTML = `<p class="hint-note">${msg}</p>`;
  };

  if (!wasm) {
    title.textContent = "Hint";
    note("The solver is still loading. Try again in a moment.");
    dialog.showModal();
    return;
  }

  // Placed digits only (givens + the player's entries). The solver derives
  // candidates itself, so pencil marks are deliberately not sent.
  const cells = new Uint8Array(N);
  for (let i = 0; i < N; i++) cells[i] = digitAt(i);

  let board;
  try {
    board = new wasm.Board(cells);
  } catch (e) {
    title.textContent = "Hint";
    note(`That board isn't valid: ${escapeHtml(String(e))}`);
    dialog.showModal();
    return;
  }

  // `steps` are plain JS objects (nothing to free); the Board handle lives in
  // wasm linear memory, so free it once we've read what we need.
  let steps, solved;
  try {
    steps = wasm.hint(board);
    solved = board.isSolved();
  } finally {
    board.free();
  }

  if (steps.length === 0) {
    title.textContent = solved ? "Solved" : "Stuck";
    note(
      solved
        ? "The puzzle is already solved."
        : "No technique we've implemented applies here yet."
    );
  } else {
    title.textContent = `${steps.length} step${steps.length === 1 ? "" : "s"} available`;
    const list = document.createElement("ul");
    list.className = "hint-list";
    for (const step of steps) list.appendChild(renderStep(step));
    body.replaceChildren(list);
  }
  dialog.showModal();
}

function renderStep(step) {
  const li = document.createElement("li");
  li.className = "hint-step";

  const head = document.createElement("div");
  const tech = document.createElement("span");
  tech.className = "tech";
  tech.textContent = step.technique.name;
  head.appendChild(tech);

  // "<house> @ <cells>" — whichever the step carries.
  const whereBits = [];
  if (step.house) whereBits.push(houseLabel(step.house));
  if (step.focusCells.length) whereBits.push(step.focusCells.map(cellName).join(", "));
  if (whereBits.length) {
    const where = document.createElement("span");
    where.className = "where";
    where.textContent = ` — ${whereBits.join(" @ ")}`;
    head.appendChild(where);
  }
  li.appendChild(head);

  const deds = document.createElement("div");
  deds.className = "deductions";
  deds.textContent = step.deductions.map(deductionText).join(", ");
  li.appendChild(deds);

  return li;
}

function wireHint() {
  const dialog = document.getElementById("hintDialog");
  document.getElementById("hint").addEventListener("click", showHint);
  document.getElementById("hintClose").addEventListener("click", () => dialog.close());
  // A click on the backdrop (outside the dialog box) targets the dialog itself.
  dialog.addEventListener("click", (e) => {
    if (e.target === dialog) dialog.close();
  });
}

// Generate a fresh Tier::Easy puzzle via the bridge and load it. The wasm side
// needs a seed (it can't read entropy itself on wasm), so we hand it a random
// u64. Generation is fast for Easy; other tiers may not be, and aren't wired up.
function generate() {
  if (!wasm) return;
  try {
    const seed = crypto.getRandomValues(new BigUint64Array(1))[0];
    const p = wasm.generate(seed); // { puzzle, solution, givens }
    loadPuzzle(p.puzzle, p.solution);
  } catch (e) {
    console.error("generate failed:", e);
  }
}

// Swap in a new puzzle: refresh the clues and wipe all player work (reusing
// `restart`, which clears values/marks/history and re-renders).
function loadPuzzle(puzzle, solution) {
  PUZZLE.puzzle = puzzle;
  PUZZLE.solution = solution;
  parseGivens();
  restart();
}

// ---- Wiring ----
// Double-tap detection that never delays a single tap: the first tap acts
// immediately and records how to undo itself; a second tap on the same digit
// within DOUBLE_MS rolls that back and runs the double-tap action instead.
//
// Pad gestures:
//   unlocked, tap                          -> place into the selected cell
//   unlocked, double-tap                   -> pen-lock that digit
//   locked,   tap                          -> unlock (place nothing)
//   locked,   double-tap (same digit)      -> unlock
//   locked,   double-tap (different digit) -> switch the lock to that digit
const DOUBLE_MS = 280;
let lastDigit = 0;
let lastTapTime = 0;
// How to undo the most recent single tap if it turns out to be a double:
let firstTapWasLocked = false; // the tap happened while locked (it unlocked)
let prevLock = 0; // the digit that was locked before that unlock
let digitSinglePushed = false; // the single tap placed a digit (undo entry exists)

function onDigitTap(d) {
  const now = performance.now();
  const isDouble = d === lastDigit && now - lastTapTime < DOUBLE_MS;
  lastTapTime = now;

  if (isDouble) {
    lastDigit = 0; // don't let a third quick tap read as another double
    if (firstTapWasLocked) {
      // The first tap already unlocked `prevLock`. Same digit -> stay
      // unlocked; a different digit -> switch the lock to it.
      setLock(d === prevLock ? 0 : d);
    } else {
      // The first tap placed into the selected cell -> roll that back (it was
      // recorded on the undo stack), then pen-lock instead. Net: no edit.
      if (digitSinglePushed) {
        applySnapshot(history.pop());
        digitSinglePushed = false;
        updateUndoButton();
      }
      setLock(d);
    }
    return;
  }

  // First tap: act immediately, remembering how a follow-up double undoes it.
  lastDigit = d;
  if (activeDigit !== 0) {
    firstTapWasLocked = true;
    prevLock = activeDigit;
    digitSinglePushed = false;
    setLock(0); // unlock now; place nothing
  } else {
    firstTapWasLocked = false;
    prevLock = 0;
    digitSinglePushed = inputDigit(d);
  }
}

function wirePad() {
  for (const btn of document.querySelectorAll(".key[data-digit]")) {
    const d = Number(btn.dataset.digit);
    digitBtns[d - 1] = btn;
    btn.addEventListener("click", () => onDigitTap(d));
  }
  document.getElementById("erase").addEventListener("click", erase);
  notesBtn.addEventListener("click", toggleNotes);
  if (undoBtn) undoBtn.addEventListener("click", undo);
}

function wireKeyboard() {
  window.addEventListener("keydown", (e) => {
    if (e.key >= "1" && e.key <= "9") {
      inputDigit(Number(e.key));
    } else if (e.key === "0" || e.key === "Backspace" || e.key === "Delete") {
      erase();
    } else if (e.key === "ArrowUp") {
      moveSelection(-1, 0);
    } else if (e.key === "ArrowDown") {
      moveSelection(1, 0);
    } else if (e.key === "ArrowLeft") {
      moveSelection(0, -1);
    } else if (e.key === "ArrowRight") {
      moveSelection(0, 1);
    } else if (e.key === "n" || e.key === "N") {
      toggleNotes();
    } else if ((e.ctrlKey || e.metaKey) && (e.key === "z" || e.key === "Z")) {
      undo();
    } else {
      return;
    }
    e.preventDefault();
  });
}

// The top bar: a (stubbed) home button and an overflow menu.
function wireTopbar() {
  const homeBtn = document.getElementById("home");
  const menuBtn = document.getElementById("menuBtn");
  const menuList = document.getElementById("menuList");

  const closeMenu = () => {
    menuList.hidden = true;
    menuBtn.setAttribute("aria-expanded", "false");
  };

  menuBtn.addEventListener("click", (e) => {
    e.stopPropagation(); // don't let the document handler immediately re-close
    const open = menuList.hidden;
    menuList.hidden = !open;
    menuBtn.setAttribute("aria-expanded", String(open));
  });

  menuList.addEventListener("click", (e) => {
    const item = e.target.closest(".menu-item");
    if (!item) return;
    if (item.dataset.action === "restart") restart();
    else if (item.dataset.action === "generate") generate();
    closeMenu();
  });

  // Dismiss the menu on any outside click or Escape.
  document.addEventListener("click", closeMenu);
  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") closeMenu();
  });

  homeBtn.addEventListener("click", () => {
    // TODO: navigate to the home / stage-select screen once it exists.
  });
}

// ---- Boot ----
parseGivens();
buildBoard();
wirePad();
wireKeyboard();
wireTopbar();
wireHint();
updateUndoButton();
render();
