// Solve-log backend client. Posts a solved game to the Cloudflare Worker
// (see docs/backend-prototype.md), now with offline durability: a failed or
// offline POST is queued in a localStorage outbox and retried -- lazily on the
// next solve (batched with it over the already batch-capable endpoint), on the
// `online` event, and once on load. Re-sends are idempotent server-side
// (solve_id + INSERT OR IGNORE), so an over-eager retry just writes nothing.
//
// Failures that reach the server but are rejected (a 4xx that isn't auth, or a
// 5xx) -- and solves that fail client-side validation -- are also reported to a
// sibling /errors endpoint, so the rejected payload is inspectable in the backend
// without touching the device. Offline (network-reject) failures aren't reported:
// there is no network to report over, they just stay queued for the next retry.
//
// This module also syncs the player's MOVE TIMELINE (recordMoves -> /moves), not
// just the final solve: whole-timeline snapshots are uploaded periodically during
// play and on close so an abandoned or in-progress puzzle is still captured. That
// path has its own coalescing outbox; see the Move-log outbox section below.

// Build-time source commit (short HEAD, '-dirty' for a modified tree, or
// "unknown" off-git). Generated by the Trunk pre_build hook, gitignored. Sent
// as client_version so a row can be traced to the exact frontend that wrote it.
import VERSION from "./version.js";

// Worker endpoint + shared key, generated into the gitignored backend-config.js
// by a Trunk pre_build hook (see Trunk.toml). Defaults are the production
// placeholders; SUDOKU_BACKEND_ENDPOINT / SUDOKU_API_KEY in the build env
// override them, so scripts/dev-local retargets the build at a local worker with
// no source edit. Both are public in the shipped bundle by necessity: there is
// no server-side render to inject them, and the key only buys a speed bump
// against drive-by bots (a human with devtools can read it). Public-writable.
import { ENDPOINT, API_KEY } from "./backend-config.js";

// Per-POST console logging is gated on cheat/debug mode (cheat.js): on by default
// on private/dev hosts (localhost + LAN, so dev-local logs for free) and off on
// the public site unless explicitly flipped on -- keeps end users' consoles quiet
// while staying available for debugging prod.
import { cheatOn } from "./cheat.js";

// The user's explicit opt-in to data sharing (Settings -> Share play data),
// default OFF. Posting is gated on this on TOP of CONFIGURED, so an opted-out
// user -- the default -- never enqueues or sends anything: no data leaves the
// device. settings.js is DOM-free, so importing it here is safe.
import { dataSharingOn } from "./settings.js";

// True until the constants above are replaced with the deployed values. While
// unconfigured we skip the POST entirely so the prototype doesn't fire a doomed
// request (and log a console error) on every solve before the backend exists.
const CONFIGURED = !ENDPOINT.includes("<subdomain>") && !API_KEY.includes("<paste");

// Posting requires BOTH a configured backend AND the user's opt-in. Checked at
// every enqueue and every flush, so flipping the setting off stops sends at once
// and a never-opted-in user queues nothing.
function postingEnabled() {
  return CONFIGURED && dataSharingOn();
}

// The failure-capture endpoint is the solve endpoint's sibling on the same
// worker: /solves -> /errors, same key. Derived here so the generated
// backend-config.js (and its build hook) needs no change.
const ERRORS_ENDPOINT = ENDPOINT.replace(/\/solves$/, "/errors");

// Outbox: a localStorage queue of unsent payloads. Bounded so a permanently
// unreachable backend can't grow it without limit (or blow the keepalive body
// cap); on overflow the OLDEST entries are dropped (a fresh solve is worth more
// than a long-stale one). Same try/catch-guarded idiom as store.js -- a quota or
// privacy-mode failure degrades to "this session isn't durable", never throws.
const OUTBOX_KEY = "sudoku.backend.outbox.v1";
const OUTBOX_MAX = 100;

function loadOutbox() {
  let raw;
  try { raw = localStorage.getItem(OUTBOX_KEY); } catch { return []; }
  if (!raw) return [];
  try {
    const entries = JSON.parse(raw);
    return Array.isArray(entries) ? entries : [];
  } catch {
    return [];
  }
}

function saveOutbox(entries) {
  try {
    localStorage.setItem(OUTBOX_KEY, JSON.stringify(entries));
  } catch {
    // Quota or privacy mode: durability is best-effort; the solve flow is unaffected.
  }
}

// Drop the given solve_ids from the outbox, re-reading current state first so a
// solve enqueued while a POST was in flight isn't clobbered by a stale snapshot.
function removeFromOutbox(ids) {
  const drop = new Set(ids);
  saveOutbox(loadOutbox().filter((e) => !drop.has(e.solve_id)));
}

// Mirror of the worker's valid(): a payload that would fail server validation is
// caught here so one bad entry can't 400 the whole batch (and block the good
// solves queued behind it). seed is optional; client_version is stamped by us.
function validPayload(s) {
  return !!s
    && typeof s.solve_id === "string" && s.solve_id.length > 0
    && typeof s.puzzle === "string"   && s.puzzle.length === 81
    && typeof s.solution === "string" && s.solution.length === 81
    && Number.isInteger(s.solve_ms)
    && (s.seed == null || typeof s.seed === "string");
}

// Best-effort failure report to /errors. Fire-and-forget, never throws, and has
// no outbox of its own -- a lost error report is simply lost (we never recurse
// failures into more failures). No keepalive: it's diagnostic, so we'd rather not
// stack its body against the solve POST under the shared keepalive size cap.
function reportFailure(detail) {
  if (!CONFIGURED) return;
  const debug = cheatOn();
  try {
    fetch(ERRORS_ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json", "x-api-key": API_KEY },
      body: JSON.stringify({ ...detail, client_version: VERSION, user_agent: navigator.userAgent }),
    })
      .then((resp) => { if (debug) console.log(`[backend] error report -> ${resp.status}`); })
      .catch((err) => { if (debug) console.warn("[backend] error report failed:", err); });
  } catch (err) {
    if (debug) console.warn("[backend] error report threw:", err);
  }
}

// Capture a kept (retryable) failure at most once. Reports only the still-queued
// entries that haven't been flagged yet, then marks them, so a persistently 5xx
// batch retried on every solve/online/load doesn't spam /errors with duplicates.
function reportFailureOnce(ids, detail) {
  const current = loadOutbox();
  const inBatch = new Set(ids);
  const unreported = current.filter((e) => inBatch.has(e.solve_id) && !e.errorReported);
  if (!unreported.length) return;
  reportFailure({ ...detail, solves: unreported });
  for (const e of current) if (inBatch.has(e.solve_id)) e.errorReported = true;
  saveOutbox(current);
}

// A flush is in progress; serialize so the online/load triggers don't double-POST
// against a concurrent recordSolve. A request that arrives mid-flush sets
// flushAgain so the queue is re-checked once the current send settles.
let flushing = false;
let flushAgain = false;

// Send the whole outbox in one batch and reconcile the queue with the outcome:
//   2xx              -> delivered; drop the sent entries.
//   401              -> bad/missing key (visible in the dashboard, and the /errors
//                       endpoint would 401 too) -> keep, don't report; a corrected
//                       build picks the queue back up on reload.
//   other 4xx (400)  -> permanent client error -> capture the rejected payload to
//                       /errors, then drop so it can't wedge the queue forever.
//   5xx              -> transient server error -> keep for retry, capture once.
//   network reject   -> offline/unreachable -> keep for retry, don't report.
async function flushOutbox() {
  if (!postingEnabled()) return;
  if (flushing) { flushAgain = true; return; }
  const batch = loadOutbox();
  if (!batch.length) return;
  flushing = true;
  const debug = cheatOn();
  const sentIds = batch.map((e) => e.solve_id);
  try {
    const resp = await fetch(ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json", "x-api-key": API_KEY },
      body: JSON.stringify({ solves: batch }),
      keepalive: true,
    });
    if (debug) {
      let body = "";
      try { body = await resp.text(); } catch {}
      console.log(`[backend] solves POST (${batch.length}) -> ${resp.status} ${body}`.trimEnd());
    }
    if (resp.ok) {
      removeFromOutbox(sentIds);
    } else if (resp.status === 401) {
      // Keep: don't lose solves to a deploy-time key mismatch; a fixed build delivers them.
    } else if (resp.status < 500) {
      reportFailure({ kind: "solve_post_rejected", status: resp.status, solves: batch });
      removeFromOutbox(sentIds);
    } else {
      reportFailureOnce(sentIds, { kind: "solve_post_server_error", status: resp.status });
    }
  } catch (err) {
    // Offline / network reject: keep for retry, nothing to report over.
    if (debug) console.warn("[backend] solves POST failed (queued for retry):", err);
  } finally {
    flushing = false;
    if (flushAgain) { flushAgain = false; flushOutbox(); }
  }
}

// Record a solved game. Enqueue-then-flush: the solve is persisted to the outbox
// FIRST (so it survives a closed tab or a never-resolving POST), then the whole
// queue is flushed in one batch. Fire-and-forget: recording a solve must never
// affect the solve flow, so this never throws and never awaits into the UI.
// `solve` is { solve_id, seed, puzzle, solution, solve_ms }.
export function recordSolve(solve) {
  if (!postingEnabled()) {
    if (cheatOn()) console.log(`[backend] solve not recorded: ${CONFIGURED ? "sharing off" : "backend not configured"}`);
    return;
  }
  const entry = { ...solve, client_version: VERSION };
  if (!validPayload(entry)) {
    // Would fail server validation -> don't poison the batch with it; capture it
    // instead so the malformed solve is still visible in the backend.
    if (cheatOn()) console.warn("[backend] solve failed client validation; not queued:", entry);
    reportFailure({ kind: "invalid_solve", solve: entry });
    return;
  }
  const outbox = loadOutbox();
  outbox.push(entry);
  saveOutbox(outbox.length > OUTBOX_MAX ? outbox.slice(outbox.length - OUTBOX_MAX) : outbox);
  flushOutbox();
}

// ---- Move-log outbox ----
// The player's move timeline (see tracker.js / play.js), synced periodically DURING
// play and on close -- not just at solve -- so an abandoned or in-progress puzzle
// still shows where people stalled. Unlike a solve (append-only, one row each) a
// move log is a whole-timeline SNAPSHOT that grows as play continues and is re-sent
// at each sync point, so this outbox COALESCES by solve_id: enqueuing a newer
// snapshot for a solve_id replaces the one already queued for it (latest wins),
// bounding the queue to one entry per puzzle in flight. The server upsert is
// idempotent and guarded against shrinking the stored log, so an over-eager or
// out-of-order retry is harmless. Sibling endpoint of /solves on the same worker.
const MOVES_ENDPOINT = ENDPOINT.replace(/\/solves$/, "/moves");
const MOVE_OUTBOX_KEY = "sudoku.backend.moves.outbox.v1";
const MOVE_OUTBOX_MAX = 50; // distinct puzzles; coalescing bounds per-puzzle growth

function loadMoveOutbox() {
  let raw;
  try { raw = localStorage.getItem(MOVE_OUTBOX_KEY); } catch { return []; }
  if (!raw) return [];
  try {
    const entries = JSON.parse(raw);
    return Array.isArray(entries) ? entries : [];
  } catch {
    return [];
  }
}

function saveMoveOutbox(entries) {
  try {
    localStorage.setItem(MOVE_OUTBOX_KEY, JSON.stringify(entries));
  } catch {
    // Quota or privacy mode: durability is best-effort; the play flow is unaffected.
  }
}

// Drop delivered snapshots, KEEPING any that grew since they were sent: a snapshot
// re-enqueued by a sync that landed mid-flush carries more events than the one we
// delivered, so comparing event counts (not just solve_id) preserves it. Re-reads
// current state so a concurrent recordMoves isn't clobbered by a stale snapshot.
function removeDeliveredMoves(sent) {
  saveMoveOutbox(loadMoveOutbox().filter((e) => {
    const n = sent.get(e.solve_id);
    return n === undefined || (Array.isArray(e.events) && e.events.length > n);
  }));
}

// Mirror of the worker's validLog(): an in-progress timeline always carries at
// least its opening `session` event, so events is non-empty; seed is optional and
// client_version/last_t are stamped by recordMoves.
function validLog(s) {
  return !!s
    && typeof s.solve_id === "string" && s.solve_id.length > 0
    && typeof s.puzzle === "string"   && s.puzzle.length === 81
    && Array.isArray(s.events) && s.events.length > 0
    && (s.seed == null || typeof s.seed === "string");
}

let flushingMoves = false;
let flushMovesAgain = false;

// Send the whole move outbox in one batch and reconcile by event count:
//   2xx              -> delivered; drop sent snapshots, keep any that grew meanwhile.
//   401              -> bad/missing key -> keep; a corrected build picks them up.
//   other 4xx        -> permanent client error -> capture a COMPACT summary (not the
//                       full timelines -- they'd blow the /errors blob cap) and drop.
//   5xx              -> transient -> keep for retry. No once-report: move logs re-sync
//                       constantly, so a persistent 5xx would spam /errors; just keep.
//   network reject   -> offline/unreachable -> keep for retry, don't report.
async function flushMoveOutbox() {
  if (!postingEnabled()) return;
  if (flushingMoves) { flushMovesAgain = true; return; }
  const batch = loadMoveOutbox();
  if (!batch.length) return;
  flushingMoves = true;
  const debug = cheatOn();
  const sent = new Map(batch.map((e) => [e.solve_id, e.events.length]));
  try {
    const resp = await fetch(MOVES_ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json", "x-api-key": API_KEY },
      body: JSON.stringify({ logs: batch }),
      keepalive: true,
    });
    if (debug) {
      let body = "";
      try { body = await resp.text(); } catch {}
      console.log(`[backend] moves POST (${batch.length}) -> ${resp.status} ${body}`.trimEnd());
    }
    if (resp.ok) {
      removeDeliveredMoves(sent);
    } else if (resp.status === 401) {
      // Keep: don't lose timelines to a deploy-time key mismatch.
    } else if (resp.status < 500) {
      reportFailure({
        kind: "moves_post_rejected",
        status: resp.status,
        logs: batch.map((e) => ({ solve_id: e.solve_id, event_count: e.events.length, last_t: e.last_t })),
      });
      removeDeliveredMoves(sent);
    } else {
      // 5xx: keep for the next retry; nothing reported (see header).
    }
  } catch (err) {
    if (debug) console.warn("[backend] moves POST failed (queued for retry):", err);
  } finally {
    flushingMoves = false;
    if (flushMovesAgain) { flushMovesAgain = false; flushMoveOutbox(); }
  }
}

// Record (sync) a move timeline snapshot for one puzzle. Enqueue-then-flush like
// recordSolve, but coalescing: a previously queued snapshot for the same solve_id
// is dropped in favour of this newer one. Fire-and-forget: never throws, never
// awaits into the UI. `log` is { solve_id, puzzle, seed, solved, events } where
// `events` is the full timeline array (tracker.snapshot()).
export function recordMoves(log) {
  if (!postingEnabled()) {
    if (cheatOn()) console.log(`[backend] moves not recorded: ${CONFIGURED ? "sharing off" : "backend not configured"}`);
    return;
  }
  const events = Array.isArray(log && log.events) ? log.events : [];
  const entry = {
    solve_id: log.solve_id,
    puzzle: log.puzzle,
    seed: log.seed ?? null,
    solved: !!log.solved,
    // Last event's solve-elapsed ms -- a progress signal the server stores without
    // parsing the timeline. Already integer ms in the tracker; round defensively.
    last_t: events.length ? Math.round(events[events.length - 1].t) : 0,
    events,
    client_version: VERSION,
  };
  if (!validLog(entry)) {
    if (cheatOn()) console.warn("[backend] move log failed client validation; not queued:", entry);
    return;
  }
  const outbox = loadMoveOutbox().filter((e) => e.solve_id !== entry.solve_id);
  outbox.push(entry);
  saveMoveOutbox(outbox.length > MOVE_OUTBOX_MAX ? outbox.slice(outbox.length - MOVE_OUTBOX_MAX) : outbox);
  flushMoveOutbox();
}

// Forget everything queued for upload. Called when the user opts OUT of sharing
// (Settings -> Share play data) so "off" leaves nothing pending on the device --
// not even a stale snapshot from a session when sharing was on. Best-effort and
// quota-safe like the other writes; clearing the queues never affects play.
export function clearOutboxes() {
  try { localStorage.removeItem(OUTBOX_KEY); } catch {}
  try { localStorage.removeItem(MOVE_OUTBOX_KEY); } catch {}
}

// Retry triggers beyond the lazy next-solve/next-sync flush: drain both queues when
// connectivity returns, and once on load (a tab opened fresh while already online
// sees no `online` transition, so without this a queue left by a previous session
// would sit until the next solve/sync). All no-op when unconfigured or empty.
if (typeof window !== "undefined") {
  window.addEventListener("online", () => { flushOutbox(); flushMoveOutbox(); });
  flushOutbox();
  flushMoveOutbox();
}
