// Solve-log backend client. Posts a solved game to the Cloudflare Worker
// (see docs/backend-prototype.md). Online-only by design: a missed POST is
// simply lost for now -- offline durability (an outbox + retry over the
// already batch-capable endpoint) is a deferred, frontend-only addition.

// Build-time source commit (short HEAD, '-dirty' for a modified tree, or
// "unknown" off-git). Generated by the Trunk pre_build hook, gitignored. Sent
// as client_version so a row can be traced to the exact frontend that wrote it.
import VERSION from "./version.js";

// Worker endpoint + shared key, generated into the gitignored backend-config.js
// by a Trunk pre_build hook (see Trunk.toml). Defaults are the production
// placeholders; SUDOKU_BACKEND_ENDPOINT / SUDOKU_API_KEY in the build env
// override them, so scripts/dev-local retargets the build at a local worker with
// no source edit. Both are public in the shipped bundle by necessity: there is
// no server-side render to inject them, and the key only buys a speed bump
// against drive-by bots (a human with devtools can read it). Public-writable.
import { ENDPOINT, API_KEY } from "./backend-config.js";

// Per-POST console logging is gated on cheat/debug mode (cheat.js): on by default
// on private/dev hosts (localhost + LAN, so dev-local logs for free) and off on
// the public site unless explicitly flipped on -- keeps end users' consoles quiet
// while staying available for debugging prod.
import { cheatOn } from "./cheat.js";

// True until the constants above are replaced with the deployed values. While
// unconfigured we skip the POST entirely so the prototype doesn't fire a doomed
// request (and log a console error) on every solve before the backend exists.
const CONFIGURED = !ENDPOINT.includes("<subdomain>") && !API_KEY.includes("<paste");

// Fire-and-forget: recording a solve must never affect the solve flow, so this
// never throws and never awaits into the UI. An offline, slow, or failed POST
// is swallowed. `keepalive` lets the request outlive any navigation the solved
// dialog triggers. `solve` is { solve_id, seed, puzzle, solution, solve_ms };
// client_version is stamped here so the call site stays domain-only.
export function recordSolve(solve) {
  const debug = cheatOn();
  if (!CONFIGURED) {
    if (debug) console.log("[backend] solve not recorded: backend not configured");
    return;
  }
  try {
    fetch(ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json", "x-api-key": API_KEY },
      body: JSON.stringify({ solves: [{ ...solve, client_version: VERSION }] }),
      keepalive: true,
    })
      .then(async (resp) => {
        // Read the body and log only under debug; production stays silent.
        if (!debug) return;
        let body = "";
        try { body = await resp.text(); } catch {}
        console.log(`[backend] solve POST -> ${resp.status} ${body}`.trimEnd());
      })
      .catch((err) => {
        // Still swallowed -- never affects the solve flow; only surfaced in debug.
        if (debug) console.warn("[backend] solve POST failed:", err);
      });
  } catch (err) {
    if (debug) console.warn("[backend] solve POST threw:", err);
  }
}
